# Generated by Django 4.0.1 on 2022-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league_season',
            field=models.IntegerField(),
        ),
    ]
